name: huset
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  
  #Localization & Internalization
  flutter_localization: ^0.2.0
  intl: ^0.18.1
  #Bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  #Code generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  #Dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  #Routing
  auto_route: ^7.8.4
  #UI
  flutter_svg: ^2.0.9
  #Storages
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  #Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  #Object Comparison
  equatable: ^2.0.5

dev_dependencies:
  freezed: ^2.4.5
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lint: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/svgs/